name: Generate Release Notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  OWNER: 'kts6056'
  REPO: 'release-note-test'
  TOKEN: ${{ secrets.PAT }}

jobs:
  generate-notes:
    permissions:
        contents: write
        pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            token: ${{ env.TOKEN }}
            
      - name: Get App Version
        run: |
          echo "VERSION_NAME=23.4.0" >> $GITHUB_ENV
          echo "VERSION_CODE=230400" >> $GITHUB_ENV

      - name: Get Release Notes
        id: get-notes
        run: |
          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/releases/generate-notes \
            -d '{"tag_name":"${{ env.VERSION_CODE }}","target_commitish":"main"}')

          echo "RESPONSE: $RESPONSE"
          NAME=$(echo "$RESPONSE" | jq -r .name)
          BODY=$(echo "$RESPONSE" | jq -r .body)
          echo "RELEASE_NAME: $NAME"
          echo "RELEASE_BODY: $BODY"
          echo "RELEASE_NAME=$NAME" >> $GITHUB_ENV
          echo "RELEASE_BODY=$BODY" >> $GITHUB_ENV

      - name: Display Variables
        run: |
          echo "Release Name: $RELEASE_NAME"
          echo "Release Body: $RELEASE_BODY"
