name: Generate Release Notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OWNER: 'kts6056'
  REPO: 'release-note-test'
  TARGET_BRANCH: 'main'
  TOKEN: ${{ secrets.PAT }}

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            token: ${{ env.TOKEN }}
            
      - name: Get App Version
        run: |
          echo "VERSION_NAME=23.4.0" >> $GITHUB_ENV
          echo "VERSION_CODE=230400" >> $GITHUB_ENV

      - name: Create Release Note
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases \
            -d '{"tag_name":"${{ env.VERSION_CODE }}","target_commitish":"${{ env.TARGET_BRANCH }}","name":"${{ env.VERSION_NAME }}","draft":false,"prerelease":true,"generate_release_notes":true}'